spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${datasource}
    username: root
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate.ddl-auto: create
  servlet:
    multipart:
      max-file-size: 15MB # 단일 파일 업로드 용량 제한, default : 1mb
      max-request-size: 15MB  # 모든 파일 업로드 용량 제한, default : 1mb
mail:
  address:
    admin: admin@gmail.com  # 관리자 권한
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
cloud:
  aws:
    credentials:
      access-key: ${s3.accesskey}
      secret-key: ${s3.secretkey}
    s3:
      bucket: ${s3.bucket}
    region.static: ${s3.resion}
    stack.auto: false
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error