spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${datasource}
    username: root
    password:
  batch:
    jdbc:
      initialize-schema: always
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate.ddl-auto: create
  servlet:
    multipart:
      max-file-size: 5MB # 단일 파일 업로드 용량 제한, default : 1mb
      max-request-size: 5MB  # 모든 파일 업로드 용량 제한, default : 1mb
  redis:
    host: localhost
    port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${google.clientid}
            clientSecret: ${google.clientsecret}
            scope: email, profile
mail:
  address:
    admin: admin@gmail.com  # 관리자 권한
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
cloud:
  aws:
    credentials:
      access-key: ${s3.accesskey}
      secret-key: ${s3.secretkey}
    s3.bucket: ${s3.bucket}
    region.static: ${s3.region}
    stack.auto: false
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error